-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 12:12:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lisenupdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lisenupdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lisenupdb` DEFAULT CHARACTER SET utf8 ;
USE `lisenupdb` ;

-- -----------------------------------------------------
-- Table `lisenupdb`.`users_all`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lisenupdb`.`users_all` (
  `ua_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(30) NOT NULL,
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified_by` VARCHAR(30) NOT NULL,
  `ua_username` VARCHAR(30) NOT NULL,
  `ua_firstname` VARCHAR(45) NOT NULL,
  `ua_lastname` VARCHAR(45) NOT NULL,
  `ua_email` VARCHAR(254) NOT NULL,
  `ua_password` VARCHAR(256) NOT NULL,
  `ua_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ua_id`),
  UNIQUE INDEX `ua_uk1` (`ua_username` ASC),
  UNIQUE INDEX `ua_uk2` (`ua_email` ASC));


-- -----------------------------------------------------
-- Table `lisenupdb`.`user_groups_all`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lisenupdb`.`user_groups_all` (
  `uga_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ua_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(30) NOT NULL,
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified_by` VARCHAR(30) NOT NULL,
  `uga_name` VARCHAR(45) NOT NULL,
  `uga_desc` VARCHAR(256) NOT NULL,
  `uga_slug` VARCHAR(19) NOT NULL,
  `uga_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`uga_id`),
  INDEX `uga_ua_fk_idx` (`ua_id` ASC),
  UNIQUE INDEX `uga_uk1` (`ua_id` ASC, `uga_slug` ASC),
  CONSTRAINT `uga_ua_fk`
    FOREIGN KEY (`ua_id`)
    REFERENCES `lisenupdb`.`users_all` (`ua_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lisenupdb`.`group_questions_all`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lisenupdb`.`group_questions_all` (
  `gqa_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uga_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(30) NOT NULL,
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified_by` VARCHAR(30) NOT NULL,
  `gqa_title` VARCHAR(45) NOT NULL,
  `gqa_text` TEXT NOT NULL,
  PRIMARY KEY (`gqa_id`),
  INDEX `gqa_uga_fk_idx` (`uga_id` ASC),
  CONSTRAINT `gqa_uga_fk`
    FOREIGN KEY (`uga_id`)
    REFERENCES `lisenupdb`.`user_groups_all` (`uga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lisenupdb`.`question_feedback_all`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lisenupdb`.`question_feedback_all` (
  `qfa_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gqa_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(30) NOT NULL,
  `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified_by` VARCHAR(30) NOT NULL,
  `qfa_ip_addr` VARCHAR(39) NOT NULL,
  `qfa_text` TEXT NOT NULL,
  PRIMARY KEY (`qfa_id`),
  INDEX `qfa_gqa_fk_idx` (`gqa_id` ASC),
  CONSTRAINT `qfa_gqa_fk`
    FOREIGN KEY (`gqa_id`)
    REFERENCES `lisenupdb`.`group_questions_all` (`gqa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
